# <center>**Tugas Latihan 3 DAA**</center>
<hr>

**Nama**   : John Bryan Khornelius<br>
**NIM**    : 2022071034<br>
**Kelas**  : Desain Analisis Algoritma - INF A<br>

In [1]:
# Slide 5
aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [2]:
# Latihan 1 (Slide 6)
import time

Mahasiswa = [
    "John Bryan Khornelius",
    "2022071034",
    "Informatika",
    "Desain Analisis Algoritma",
    time.ctime(),
    "Universitas Pembangunan Jaya"
]

print(Mahasiswa)

['John Bryan Khornelius', '2022071034', 'Informatika', 'Desain Analisis Algoritma', 'Fri Sep 15 14:09:47 2023', 'Universitas Pembangunan Jaya']


In [3]:
# Slide 7
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[1]

'Green'

In [4]:
# Latihan 2 (Slide 8)
import time

Mahasiswa = [
    "John Bryan Khornelius",
    "2022071034",
    "Informatika",
    "Desain Analisis Algoritma",
    time.ctime(),
    "Universitas Pembangunan Jaya"
]
# Mencetak NIM dari list mahasiswa
Mahasiswa[1]

'2022071034'

In [5]:
# Latihan 3 (Slide 9)
import time

Mahasiswa = [
    "John Bryan Khornelius",
    "2022071034",
    "Informatika",
    "Desain Analisis Algoritma",
    time.ctime(),
    "Universitas Pembangunan Jaya"
]
# Mencetak nama universitas dari list mahasiswa
Mahasiswa[5]

'Universitas Pembangunan Jaya'

In [6]:
# Slide 10
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
bin_colors[0:2]

['Red', 'Green']

In [9]:
# Latihan 4 (Slide 11)
import time

Mahasiswa = [
    "John Bryan Khornelius",
    "2022071034",
    "Informatika",
    "Desain Analisis Algoritma",
    time.ctime(),
    "Universitas Pembangunan Jaya"
]
# Mencetak NIM dan prodi dari list mahasiswa menggunakan slicing
Mahasiswa[1:3]

['2022071034', 'Informatika']

In [10]:
# Slide 12
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [12]:
# Latihan 5 (Slide 13)
import time

Mahasiswa = [
    "John Bryan Khornelius",
    "2022071034",
    "Informatika",
    "Desain Analisis Algoritma",
    time.ctime(),
    "Universitas Pembangunan Jaya"
]
# Mencetak isi list mahasiswa dengan menambahkan kata "UPJ" di depan
for data_mhs in Mahasiswa:
    print("UPJ " + data_mhs)

UPJ John Bryan Khornelius
UPJ 2022071034
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ Fri Sep 15 14:17:39 2023
UPJ Universitas Pembangunan Jaya


In [17]:
# Slide 14
bin_colors = ('Red', 'Green', 'Blue', 'Yellow')
print(bin_colors[1])
print(bin_colors[2:])

Green
('Blue', 'Yellow')


In [20]:
# Latihan 6 (Slide 15)
UPJ = ('Universitas', 'Pembangunan Jaya')
UPJ[0:]

('Universitas', 'Pembangunan Jaya')

In [21]:
# Slide 15
hariAwal = ("senin", "selasa", "rabu")
hariAkhir = ("kamis", "jumat", "sabtu")

hari = (hariAwal, hariAkhir)
print(hari)

(('senin', 'selasa', 'rabu'), ('kamis', 'jumat', 'sabtu'))


In [23]:
# Latihan 7 (Slide 17)
Pertama = (100,)
Kedua = (200, 400, 600,)
Ketiga = (300,)
Keempat = (400, 800,)

nested_tuple = (Pertama, Kedua, Ketiga, Keempat)

print(nested_tuple)

((100,), (200, 400, 600), (300,), (400, 800))


In [24]:
# Slide 18
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [25]:
# Slide 19
bin_colors.get('approved_color')
bin_colors['approved_color']

'Green'

In [26]:
# Slide 20
bin_colors['approved_color'] = "Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [27]:
# Latihan 8 (Slide 21)
mahasiswa = {
    "Nama": "John Bryan Khornelius",
    "NIM": "2022071034",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(mahasiswa)

{'Nama': 'John Bryan Khornelius', 'NIM': '2022071034', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [28]:
# Slide 22
acak = (True, {'name': 'depotkode', 'status': 'alive'}, [1, 2, 3])

In [29]:
# Slide 23
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [30]:
# Slide 24
green = {'grass', 'leaves', 'leaves'} # hanya menyimpan nilai yang berbeda dari setiap elemen
print(green)

{'leaves', 'grass'}


In [31]:
# Slide 26
# Inisiasi Set
set_01 = {4, 5, 6, 2}
print(set_01)

# inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2, 1, 4, 3]) # otomatis mengurutkan
print(type(set_02))
print(set_03)

{2, 4, 5, 6}
<class 'set'>
{1, 2, 3, 4}


In [32]:
# Slide 27
set_01 = {4, 5, 6, 2}
print(set_03[1]) # akan error, dikarenakan set merupakan struktur data yang tidak memiliki
# urutan atau index, sehingga tidak dapat mengakses angota dengan menggunakan index seperti pada list
# atau tuple, karena tidak dapat memiliki index, maka untuk menghapus anggota set
# menggunakan dua metode yaitu discard() dan remove()

TypeError: 'set' object is not subscriptable

In [33]:
# Slide 28
set_04 = {2, 3, 4, 5, 6}
set_04.add(1) # menambah anggota set dapat dilakukan dengan menggunakan metode add() yang digunakan untuk
# menambahkan hanya satu anggota pada set
print(set_04)

{1, 2, 3, 4, 5, 6}


In [34]:
# Slide 29
set_04 = {1, 2, 3, 4, 5, 6, 7, 8}
set_04.discard(4) # hapus nilai 4
print(set_04)

set_04.add(10) # menambahkan nilai 10
print(set_04)

{1, 2, 3, 5, 6, 7, 8}
{1, 2, 3, 5, 6, 7, 8, 10}


In [46]:
# Slide 30 (Union Set)
# menggabungkan semua anggota set
set_A = {1, 2, 3, 4}
set_B = {3, 4, 5, 6}
print(set_A | set_B)
print(set_A.union(set_B))

{1, 2, 3, 4, 5, 6}
{1, 2, 3, 4, 5, 6}


In [36]:
# Slide 31 (Intersection/ Irisan set)
# mencari nilai irisan dari dua buah set

print(set_A & set_B)
print(set_A.intersection(set_B))

{3, 4}
{3, 4}


In [40]:
# Slide 32 (Difference Set)
# Mencari perbedaan anggota dari dua buah set atau lebih

# A - B
print(set_A - set_B)
print(set_A.difference(set_B))

# B - A
print(set_B - set_A)
print(set_B.difference(set_A))

{1, 2}
{1, 2}
{5, 6}
{5, 6}


In [47]:
# Slide 33 (Symmetric Difference)
# semua anggota pada set A dan B dikurangi dengan anggota yang berada pada dua set tersebut

print(set_A ^ set_B)
print(set_A.symmetric_difference(set_B))

{1, 2, 5, 6}
{1, 2, 5, 6}


In [50]:
# Latihan 9 (Slide 34)
red = {'dandelions', 'leaves', 'fire hydrant'}
yellow = {'leaves', 'fire hydrant', 'rose', 'blood'}
print(yellow | red) # menggabungkan 2 set (Union)
print(yellow & red) # melihat irisan (intersection)

{'dandelions', 'fire hydrant', 'leaves', 'blood', 'rose'}
{'leaves', 'fire hydrant'}


In [51]:
# Slide 35 (Data Frame)
# struktur data yang digunakan untuk menyimpan data tabular yang
# tersedia dalam paket pandas python

import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True],
])

df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [52]:
# Slide 36
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [55]:
# Slide 37 (seleksi kolom)
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [56]:
# Slide 38
# Row Selection
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [57]:
# Slide 38
df[df.age > 30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [58]:
# Slide 38
df[(df.age < 35) & (df.decision == True)]

id   name  age  decision
0  1  Fares   32      True

In [59]:
# Slide 39
# memberikan index label seperti pada Series
data = {'satu': [1, 1, 1, 1, 1],
    'dua': [2, 2, 2, 2, 2],
    'tiga': [3, 3, 3, 3, 3]
}
df = pd.DataFrame(data, index=['a', 'b', 'c', 'd','e'])
df.head()

satu  dua  tiga
a     1    2     3
b     1    2     3
c     1    2     3
d     1    2     3
e     1    2     3

In [74]:
# Latihan 10 (Slide 41)
import pandas as pd

mhs = pd.DataFrame([
    ["Informatika", 50, 30, 20],
    ["Sistem Informasi", 55, 30, 25],
    ["Teknik Sipil", 40, 30, 10],
    ],
    index=[1, 2, 3]
)

mhs.columns = ['Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
mhs

Prodi  Mahasiswa  Lakilaki  Perempuan
1       Informatika         50        30         20
2  Sistem Informasi         55        30         25
3      Teknik Sipil         40        30         10

In [76]:
# Slide 42 (Matrix DS)
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)
print(type(myMatrix))

[[11 12 13]
 [21 22 23]
 [31 32 33]]
<class 'numpy.ndarray'>


In [78]:
# Slide 43
import numpy as np
matriksC = np.array([[1, 2, 3], [4, 5, 6]])
print("Matriks C :")
print(matriksC)

transpose_matriks = np.transpose(matriksC)

print("Transpose Matriks C :")
print(transpose_matriks)

Matriks C :
[[1 2 3]
 [4 5 6]]
Transpose Matriks C :
[[1 4]
 [2 5]
 [3 6]]


In [79]:
# Latihan 11 (Slide 44)
import numpy as np
matriks = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
])

print(f"Matriks: \n{matriks}")

# Transpose matriks
t_matriks = np.transpose(matriks)

print(f"Transpose Matriks: \n{t_matriks}")

Matriks: 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transpose Matriks: 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [80]:
# Slide 46 (Vector)
# menggunakan list python:
myVector = [22, 33, 44, 55]
print(myVector)

print(type(myVector))

[22, 33, 44, 55]
<class 'list'>


In [81]:
# Slide 46 (Vector)
# menggunakan array numpy
myVector = np.array([22, 33, 44, 55])
print(myVector)

print(type(myVector))

[22 33 44 55]
<class 'numpy.ndarray'>


In [108]:
# Slide 48 (Stack)
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

# define object from class
stack = Stack()
# stack push
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')

In [109]:
# Slide 48 (Stack)
# stack pop
stack.pop()

'Yellow'

In [110]:
# Slide 48 (Stack)
# stack isEmpty
stack.isEmpty()

False

In [111]:
# Slide 50 (Queue)
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self, item):
        self.items.insert(0, item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [112]:
# Slide 50 (Queue)
queue = Queue() # define object from class

In [113]:
# Slide 50 (Queue)
queue.enqueue('Red')

In [114]:
# Slide 50 (Queue)
queue.enqueue('Green')

In [115]:
# Slide 50 (Queue)
queue.enqueue('Blue')

In [116]:
# Slide 50 (Queue)
queue.enqueue('Yellow')

In [117]:
# Slide 50 (Queue)
print(queue.size())

4


In [118]:
# Slide 50 (Queue)
print(queue.dequeue())

Red


In [119]:
# Slide 50 (Queue)
print(queue.dequeue())

Green


In [120]:
# Slide 55 (Binary Tree pada Python)
class Node:
    def __init__(self, data):
        self.left = None
        self.right = None
        self.data = data
    def PrintTree(self):
        if self.left:
            self.left.PrintTree()
        print(self.data),
        if self.right:
            self.right.PrintTree()

root = Node(2) # root
root.left = Node(3) # child kiri dari root
root.right = Node(5) # child kanan dari root
root.left.left = Node(7) # child kiri dari 3
root.left.right = Node(9) # child kanan dari 3
root.right.left = Node(11) # child kiri dari 5
root.right.right = Node(13) # child kanan dari 5
root.PrintTree()

7
3
9
2
11
5
13
